# Generated by Django 4.0.5 on 2022-07-31 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('level', models.CharField(choices=[('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4')], max_length=150)),
                ('ncv_or_report191', models.CharField(choices=[('NCV', 'NCV'), ('191', 'Report 191 (Nated)')], max_length=150)),
                ('fundamental_or_vocational', models.CharField(choices=[('vocational', 'Vocational'), ('fundamental', 'Fundamental')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('exam_period', models.CharField(choices=[('supplementary', 'Supplementary Exam'), ('midyear_exam', 'May/June'), ('endyear_exam', 'Nov/Dec')], max_length=150)),
                ('question_paper', models.FileField(upload_to='question_papers/% Y/% m/% d/')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='papers.subject')),
            ],
        ),
    ]
