# Generated by Django 4.0.5 on 2022-08-04 04:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='date_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='exam_period',
            field=models.CharField(choices=[('supplementary Exam', 'Supplementary Exam'), ('May/June', 'May/June'), ('Nov/Dec', 'Nov/Dec')], max_length=150),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='question_paper',
            field=models.FileField(upload_to='question_papers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='fundamental_or_vocational',
            field=models.CharField(blank=True, choices=[('vocational', 'Vocational'), ('fundamental', 'Fundamental')], max_length=150),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('2', 'Level 2'), ('3', 'Level 3'), ('4', 'Level 4'), ('N4', 'N4'), ('N5', 'N5'), ('N6', 'N6')], max_length=150),
        ),
        migrations.AlterField(
            model_name='subject',
            name='ncv_or_report191',
            field=models.CharField(choices=[('NCV', 'NCV'), ('Report 191', 'Report 191 (Nated)')], max_length=150),
        ),
        migrations.CreateModel(
            name='MarkingGuideLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marking_guideline', models.FileField(upload_to='marking_guidelines/%Y/%m/%d/')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='papers.questionpaper')),
            ],
        ),
    ]
